services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dialog
      POSTGRES_PASSWORD: dialog
      POSTGRES_DB: dialog
    volumes:
       - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dialog", "-U", "dialog"]
      interval: 10s
      timeout: 5s
      retries: 5

  make-embeddings:
    build: .
    command: /app/src/scripts/make_embeddings.py
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/data

  dialog:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      make-embeddings:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/data