name: test
run-name: Build Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build test
      run: docker compose --env-file ./.env.sample -f docker-compose.yml run --rm --build dialog 